steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-class-1-427416/runimage', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-class-1-427416/runimage']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'myfirstrun', '--image', 'gcr.io/gcp-class-1-427416/runimage', '--region', 'europe-west1', '--allow-unauthenticated']

images:
- 'gcr.io/gcp-class-1-427416/runimage'

options:
  logging: CLOUD_LOGGING_ONLY
